org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
kotlin.jvm.target.validation.mode=warning
android.enableUnitTestBinaryResources=false
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderscript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
org.gradle.parallel=true
org.gradle.daemon=true
android.defaults.compileconfig.kotlinoptions.jvmtarget=1.8
